import { spawn } from "node:child_process";
import { readFile, stat, writeFile } from "node:fs/promises";
import { request } from "node:https";
import { createServer } from "node:net";
import path from "node:path";
import process from "node:process";

const devManifestPath = ".shopify/dev-bundle/manifest.json";
const hydrogenGeneratedConfigPath =
  "hydrogen-loyalty-storefront/app/lib/loyalty-app-url.generated.js";
const extensionGeneratedConfigPaths = [
  "extensions/loyalty-checkout/src/api-base-url.generated.js",
  "extensions/loyalty-account/src/api-base-url.generated.js",
];
const tunnelUrlPattern = /https:\/\/[a-z0-9-]+\.trycloudflare\.com/gi;
let currentTunnelUrl = "";
let configWrite = Promise.resolve();
let manifestPoll;
let child;
let tunnelChild;
let shopifyArgs = process.argv.slice(2);
let shopifyCliStartedAt = 0;
let retryCount = 0;
const maxQuickFailureRetries = 3;
const quickFailureRetryMs = 90_000;

function normalizeTunnelUrl(value) {
  try {
    const url = new URL(value);

    return `${url.protocol}//${url.host}`;
  } catch {
    return "";
  }
}

async function writeGeneratedTunnelUrls(tunnelUrl) {
  const hydrogenContents = `// Generated by npm run dev. Do not edit.\nexport const LOYALTY_APP_URL = ${JSON.stringify(tunnelUrl)};\n`;
  const extensionContents = `// Generated by npm run dev. Do not edit.\nexport const API_BASE_URL = ${JSON.stringify(tunnelUrl)};\n`;

  await Promise.all([
    writeFile(
      path.join(process.cwd(), hydrogenGeneratedConfigPath),
      hydrogenContents,
    ),
    ...extensionGeneratedConfigPaths.map((generatedPath) =>
      writeFile(path.join(process.cwd(), generatedPath), extensionContents),
    ),
  ]);
}

async function writeTunnelUrl(tunnelUrl, options = {}) {
  if (tunnelUrl === currentTunnelUrl && !options.force) return;

  currentTunnelUrl = tunnelUrl;
  await writeGeneratedTunnelUrls(tunnelUrl);

  process.stdout.write(
    tunnelUrl
      ? `\n[loyalty-dev] Hydrogen URL updated${options.source ? ` from ${options.source}` : ""}: ${tunnelUrl}\n`
      : "\n[loyalty-dev] Hydrogen URL cleared until a tunnel is available.\n",
  );
}

function queueTunnelUrlWrite(tunnelUrl, options = {}) {
  if (!tunnelUrl || tunnelUrl === currentTunnelUrl) return;

  configWrite = configWrite
    .then(() => writeTunnelUrl(tunnelUrl, options))
    .catch((error) => {
      process.stderr.write(
        `[loyalty-dev] Could not update extension API URL: ${error.message}\n`,
      );
    });
}

async function readManifestTunnelUrl() {
  try {
    if (!shopifyCliStartedAt) return "";

    const manifestStats = await stat(path.join(process.cwd(), devManifestPath));

    // Never propagate a URL from a previous dev session while a new tunnel is
    // still starting.
    if (manifestStats.mtimeMs < shopifyCliStartedAt) {
      return "";
    }

    const manifest = JSON.parse(
      await readFile(path.join(process.cwd(), devManifestPath), "utf8"),
    );
    const appUrl = manifest?.modules?.find(
      (module) => module?.type === "app_home",
    )?.config?.app_url;

    if (typeof appUrl === "string") {
      const tunnelUrl = normalizeTunnelUrl(appUrl);

      if (tunnelUrl.endsWith(".trycloudflare.com")) {
        return tunnelUrl;
      }
    }

    return "";
  } catch {
    return "";
  }
}

function startManifestPolling() {
  manifestPoll = setInterval(async () => {
    try {
      const tunnelUrl = await readManifestTunnelUrl();

      if (tunnelUrl) {
        queueTunnelUrlWrite(tunnelUrl, { source: "Shopify tunnel" });
      }
    } catch (error) {
      process.stderr.write(
        `[loyalty-dev] Could not read Shopify tunnel URL: ${error.message}\n`,
      );
    }
  }, 1000);
}

function getShopifyCliEnv() {
  const nodeOptions = [
    process.env.NODE_OPTIONS,
    "--dns-result-order=ipv4first",
  ]
    .filter(Boolean)
    .join(" ");

  return {
    ...process.env,
    NODE_OPTIONS: nodeOptions,
  };
}

function wait(milliseconds) {
  return new Promise((resolve) => setTimeout(resolve, milliseconds));
}

function requestQuickTunnel() {
  return new Promise((resolve, reject) => {
    const tunnelRequest = request(
      "https://api.trycloudflare.com/tunnel",
      {
        family: 4,
        method: "POST",
        timeout: 20_000,
      },
      (response) => {
        let body = "";

        response.setEncoding("utf8");
        response.on("data", (chunk) => {
          body += chunk;
        });
        response.on("end", () => {
          try {
            const payload = JSON.parse(body);

            if (!payload?.success || !payload?.result?.hostname) {
              throw new Error("Cloudflare returned an invalid tunnel response");
            }

            resolve(payload.result);
          } catch (error) {
            reject(error);
          }
        });
      },
    );

    tunnelRequest.on("timeout", () => {
      tunnelRequest.destroy(new Error("Cloudflare IPv4 request timed out"));
    });
    tunnelRequest.on("error", reject);
    tunnelRequest.end();
  });
}

async function requestQuickTunnelWithRetry() {
  let lastError;

  for (let attempt = 1; attempt <= 3; attempt += 1) {
    try {
      return await requestQuickTunnel();
    } catch (error) {
      lastError = error;
      process.stderr.write(
        `[loyalty-dev] Cloudflare IPv4 tunnel request failed (${attempt}/3): ${error.message}\n`,
      );
      if (attempt < 3) await wait(2000 * attempt);
    }
  }

  throw lastError;
}

function findAvailablePort(startPort = 4040) {
  return new Promise((resolve, reject) => {
    const server = createServer();

    server.unref();
    server.on("error", (error) => {
      if (error.code === "EADDRINUSE") {
        resolve(findAvailablePort(startPort + 1));
      } else {
        reject(error);
      }
    });
    server.listen(startPort, "127.0.0.1", () => {
      server.close(() => resolve(startPort));
    });
  });
}

async function startIpv4QuickTunnel() {
  const tunnel = await requestQuickTunnelWithRetry();
  const port = await findAvailablePort();
  const credentials = JSON.stringify({
    AccountTag: tunnel.account_tag,
    TunnelID: tunnel.id,
    TunnelSecret: tunnel.secret,
  });

  tunnelChild = spawn(
    process.env.SHOPIFY_CLI_CLOUDFLARED_PATH || "cloudflared",
    [
      "tunnel",
      "run",
      "--url",
      `http://localhost:${port}`,
      tunnel.id,
    ],
    {
      cwd: process.cwd(),
      env: {
        ...process.env,
        TUNNEL_CRED_CONTENTS: credentials,
        TUNNEL_EDGE_IP_VERSION: "4",
      },
      stdio: ["ignore", "pipe", "pipe"],
    },
  );

  await new Promise((resolve, reject) => {
    let connected = false;
    const timeout = setTimeout(() => {
      reject(new Error("Cloudflare tunnel connection timed out"));
    }, 30_000);
    const handleOutput = (chunk, output) => {
      const message = chunk.toString();
      output.write(message);

      if (!connected && message.includes("Registered tunnel connection")) {
        connected = true;
        clearTimeout(timeout);
        resolve();
      }
    };

    tunnelChild.stdout.on("data", (chunk) =>
      handleOutput(chunk, process.stdout),
    );
    tunnelChild.stderr.on("data", (chunk) =>
      handleOutput(chunk, process.stderr),
    );
    tunnelChild.on("error", (error) => {
      clearTimeout(timeout);
      reject(error);
    });
    tunnelChild.on("exit", (code) => {
      if (!connected) {
        clearTimeout(timeout);
        reject(new Error(`Cloudflare tunnel exited with code ${code}`));
      }
    });
  });

  const tunnelUrl = `https://${tunnel.hostname}`;
  await writeTunnelUrl(tunnelUrl, { source: "IPv4 Cloudflare tunnel" });
  process.stdout.write(
    `[loyalty-dev] Starting Shopify with custom tunnel ${tunnelUrl}:${port}\n`,
  );

  return `${tunnelUrl}:${port}`;
}

function startShopifyCli() {
  shopifyCliStartedAt = Date.now();
  child = spawn("shopify", ["app", "dev", ...shopifyArgs], {
    cwd: process.cwd(),
    env: getShopifyCliEnv(),
    stdio: "inherit",
  });

  child.on("error", async (error) => {
    clearInterval(manifestPoll);
    await configWrite;
    process.stderr.write(
      `[loyalty-dev] Could not start Shopify CLI: ${error.message}\n`,
    );
    process.exitCode = 1;
  });

  child.on("exit", async (code, signal) => {
    const runtimeMs = Date.now() - shopifyCliStartedAt;

    if (
      !signal &&
      code !== 0 &&
      code !== 130 &&
      code !== 143 &&
      runtimeMs < quickFailureRetryMs &&
      retryCount < maxQuickFailureRetries
    ) {
      retryCount += 1;
      process.stderr.write(
        `\n[loyalty-dev] Shopify CLI exited before dev server was ready; retrying ${retryCount}/${maxQuickFailureRetries}...\n`,
      );
      setTimeout(startShopifyCli, 2000);
      return;
    }

    clearInterval(manifestPoll);
    tunnelChild?.kill("SIGTERM");
    configWrite = configWrite.then(() => writeTunnelUrl("", { force: true }));
    await configWrite;

    if (signal) {
      process.exitCode = signal === "SIGINT" ? 130 : 143;
    } else {
      process.exitCode = code ?? 1;
    }
  });
}

async function main() {
  await writeTunnelUrl("", { force: true });
  startManifestPolling();

  const hasNetworkingFlag = shopifyArgs.some(
    (argument) =>
      argument === "--use-localhost" ||
      argument === "--tunnel-url" ||
      argument.startsWith("--tunnel-url="),
  );

  if (!hasNetworkingFlag) {
    const customTunnelUrl = await startIpv4QuickTunnel();
    shopifyArgs = [...shopifyArgs, "--tunnel-url", customTunnelUrl];
  }

  const hasThemePortFlag = shopifyArgs.some(
    (argument) =>
      argument === "--theme-app-extension-port" ||
      argument.startsWith("--theme-app-extension-port="),
  );

  if (!hasThemePortFlag) {
    const themePort = await findAvailablePort(9293);
    shopifyArgs = [
      ...shopifyArgs,
      "--theme-app-extension-port",
      String(themePort),
    ];

    if (themePort !== 9293) {
      process.stdout.write(
        `[loyalty-dev] Theme port 9293 is busy; using ${themePort} instead.\n`,
      );
    }
  }

  startShopifyCli();
}

main().catch(async (error) => {
  clearInterval(manifestPoll);
  tunnelChild?.kill("SIGTERM");
  await writeTunnelUrl("", { force: true });
  process.stderr.write(`[loyalty-dev] Startup failed: ${error.message}\n`);
  process.exitCode = 1;
});

for (const signal of ["SIGINT", "SIGTERM"]) {
  process.on(signal, () => {
    child?.kill(signal);
    tunnelChild?.kill(signal);
  });
}
