import { spawn } from "node:child_process";
import { readFile, utimes, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

const devManifestPath = ".shopify/dev-bundle/manifest.json";
const generatedConfigPaths = [
  "extensions/loyalty-checkout/src/api-base-url.generated.js",
  "extensions/loyalty-account/src/api-base-url.generated.js",
];
const extensionEntryPaths = [
  "extensions/loyalty-checkout/src/Checkout.jsx",
  "extensions/loyalty-account/src/CustomerAccount.jsx",
  "extensions/loyalty-account/src/RewardHistoryPage.jsx",
];
const tunnelUrlPattern = /https:\/\/[a-z0-9-]+\.trycloudflare\.com/gi;
let currentTunnelUrl = "";
let configWrite = Promise.resolve();
let outputBuffer = "";
let manifestPoll;
let canReadManifest = false;

function normalizeTunnelUrl(value) {
  try {
    const url = new URL(value);

    return `${url.protocol}//${url.host}`;
  } catch {
    return "";
  }
}

async function touchExtensionEntries() {
  const now = new Date();

  await Promise.all(
    extensionEntryPaths.map((relativePath) =>
      utimes(path.join(process.cwd(), relativePath), now, now),
    ),
  );
}

async function writeTunnelUrl(tunnelUrl, options = {}) {
  if (tunnelUrl === currentTunnelUrl && !options.force) return;

  currentTunnelUrl = tunnelUrl;
  const contents = `// Generated by npm run dev. Do not edit.\nexport const API_BASE_URL = ${JSON.stringify(tunnelUrl)};\n`;

  await Promise.all(
    generatedConfigPaths.map((relativePath) =>
      writeFile(path.join(process.cwd(), relativePath), contents),
    ),
  );

  if (tunnelUrl) {
    await touchExtensionEntries();
  }

  process.stdout.write(
    tunnelUrl
      ? `\n[loyalty-dev] Extension API URL updated: ${tunnelUrl}\n`
      : "\n[loyalty-dev] Extension API URL cleared until a tunnel is available.\n",
  );
}

function queueTunnelUrlWrite(tunnelUrl) {
  if (!tunnelUrl || tunnelUrl === currentTunnelUrl) return;

  configWrite = configWrite
    .then(() => writeTunnelUrl(tunnelUrl))
    .catch((error) => {
      process.stderr.write(
        `[loyalty-dev] Could not update extension API URL: ${error.message}\n`,
      );
    });
}

function writeTunnelUrlsFromOutput(chunk) {
  outputBuffer += String(chunk);
  const lines = outputBuffer.split(/\r?\n/);

  outputBuffer = lines.pop() || "";

  for (const line of lines) {
    const plainLine = line.replace(/\u001b\[[0-9;]*m/g, "");

    if (/Ready, watching for changes in your app/.test(plainLine)) {
      canReadManifest = true;
    }

    if (!/\bapp_(home|proxy)\b/.test(plainLine) && !/Using URL:/.test(plainLine)) {
      continue;
    }

    const matches = plainLine.match(tunnelUrlPattern) || [];
    tunnelUrlPattern.lastIndex = 0;

    const tunnelUrl = normalizeTunnelUrl(matches.at(-1));
    queueTunnelUrlWrite(tunnelUrl);
  }
}

async function readManifestTunnelUrl() {
  if (!canReadManifest) return "";

  try {
    const manifest = JSON.parse(
      await readFile(path.join(process.cwd(), devManifestPath), "utf8"),
    );
    const appUrl = manifest?.modules?.find(
      (module) => module?.type === "app_home",
    )?.config?.app_url;

    if (typeof appUrl === "string") {
      const tunnelUrl = normalizeTunnelUrl(appUrl);

      if (tunnelUrl.endsWith(".trycloudflare.com")) {
        return tunnelUrl;
      }
    }

    return "";
  } catch {
    return "";
  }
}

function startManifestPolling() {
  manifestPoll = setInterval(async () => {
    const tunnelUrl = await readManifestTunnelUrl();

    if (tunnelUrl) {
      queueTunnelUrlWrite(tunnelUrl);
    }
  }, 1000);
}

const child = spawn("shopify", ["app", "dev", ...process.argv.slice(2)], {
  cwd: process.cwd(),
  env: process.env,
  stdio: ["inherit", "pipe", "pipe"],
});
configWrite = configWrite.then(() => writeTunnelUrl("", { force: true }));
startManifestPolling();

child.stdout.on("data", (chunk) => {
  process.stdout.write(chunk);
  writeTunnelUrlsFromOutput(chunk);
});
child.stderr.on("data", (chunk) => {
  process.stderr.write(chunk);
  writeTunnelUrlsFromOutput(chunk);
});

for (const signal of ["SIGINT", "SIGTERM"]) {
  process.on(signal, () => child.kill(signal));
}

child.on("error", async (error) => {
  clearInterval(manifestPoll);
  await configWrite;
  process.stderr.write(`[loyalty-dev] Could not start Shopify CLI: ${error.message}\n`);
  process.exitCode = 1;
});

child.on("exit", async (code, signal) => {
  clearInterval(manifestPoll);
  configWrite = configWrite.then(() => writeTunnelUrl("", { force: true }));
  await configWrite;

  if (signal) {
    process.exitCode = signal === "SIGINT" ? 130 : 143;
  } else {
    process.exitCode = code ?? 1;
  }
});
