import { spawn } from "node:child_process";
import { readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

const devManifestPath = ".shopify/dev-bundle/manifest.json";
const hydrogenGeneratedConfigPath =
  "hydrogen-loyalty-storefront/app/lib/loyalty-app-url.generated.js";
const tunnelUrlPattern = /https:\/\/[a-z0-9-]+\.trycloudflare\.com/gi;
let currentTunnelUrl = "";
let configWrite = Promise.resolve();
let manifestPoll;
let child;
let shopifyCliStartedAt = 0;
let retryCount = 0;
const maxQuickFailureRetries = 3;
const quickFailureRetryMs = 90_000;

function normalizeTunnelUrl(value) {
  try {
    const url = new URL(value);

    return `${url.protocol}//${url.host}`;
  } catch {
    return "";
  }
}

async function writeHydrogenTunnelUrl(tunnelUrl) {
  const generatedPath = path.join(process.cwd(), hydrogenGeneratedConfigPath);
  const generatedContents = `// Generated by npm run dev. Do not edit.\nexport const LOYALTY_APP_URL = ${JSON.stringify(tunnelUrl)};\n`;

  await writeFile(generatedPath, generatedContents);
}

async function writeTunnelUrl(tunnelUrl, options = {}) {
  if (tunnelUrl === currentTunnelUrl && !options.force) return;

  currentTunnelUrl = tunnelUrl;
  await writeHydrogenTunnelUrl(tunnelUrl);

  process.stdout.write(
    tunnelUrl
      ? `\n[loyalty-dev] Hydrogen URL updated${options.source ? ` from ${options.source}` : ""}: ${tunnelUrl}\n`
      : "\n[loyalty-dev] Hydrogen URL cleared until a tunnel is available.\n",
  );
}

function queueTunnelUrlWrite(tunnelUrl, options = {}) {
  if (!tunnelUrl || tunnelUrl === currentTunnelUrl) return;

  configWrite = configWrite
    .then(() => writeTunnelUrl(tunnelUrl, options))
    .catch((error) => {
      process.stderr.write(
        `[loyalty-dev] Could not update extension API URL: ${error.message}\n`,
      );
    });
}

async function readManifestTunnelUrl() {
  try {
    const manifestStats = await stat(path.join(process.cwd(), devManifestPath));

    // Shopify CLI can reuse the manifest on a quick retry without touching its
    // mtime. Reject an old manifest only on the first attempt; after a retry,
    // the manifest belongs to the still-running dev session and is the most
    // reliable source for the active tunnel URL.
    if (manifestStats.mtimeMs < shopifyCliStartedAt && retryCount === 0) {
      return "";
    }

    const manifest = JSON.parse(
      await readFile(path.join(process.cwd(), devManifestPath), "utf8"),
    );
    const appUrl = manifest?.modules?.find(
      (module) => module?.type === "app_home",
    )?.config?.app_url;

    if (typeof appUrl === "string") {
      const tunnelUrl = normalizeTunnelUrl(appUrl);

      if (tunnelUrl.endsWith(".trycloudflare.com")) {
        return tunnelUrl;
      }
    }

    return "";
  } catch {
    return "";
  }
}

function startManifestPolling() {
  manifestPoll = setInterval(async () => {
    try {
      const tunnelUrl = await readManifestTunnelUrl();

      if (tunnelUrl) {
        queueTunnelUrlWrite(tunnelUrl, { source: "Shopify tunnel" });
      }
    } catch (error) {
      process.stderr.write(
        `[loyalty-dev] Could not read Shopify tunnel URL: ${error.message}\n`,
      );
    }
  }, 1000);
}

function getShopifyCliEnv() {
  const nodeOptions = [
    process.env.NODE_OPTIONS,
    "--dns-result-order=ipv4first",
  ]
    .filter(Boolean)
    .join(" ");

  return {
    ...process.env,
    NODE_OPTIONS: nodeOptions,
  };
}

function startShopifyCli() {
  shopifyCliStartedAt = Date.now();
  child = spawn("shopify", ["app", "dev", ...process.argv.slice(2)], {
    cwd: process.cwd(),
    env: getShopifyCliEnv(),
    stdio: "inherit",
  });

  child.on("error", async (error) => {
    clearInterval(manifestPoll);
    await configWrite;
    process.stderr.write(
      `[loyalty-dev] Could not start Shopify CLI: ${error.message}\n`,
    );
    process.exitCode = 1;
  });

  child.on("exit", async (code, signal) => {
    const runtimeMs = Date.now() - shopifyCliStartedAt;

    if (
      !signal &&
      code !== 0 &&
      code !== 130 &&
      code !== 143 &&
      runtimeMs < quickFailureRetryMs &&
      retryCount < maxQuickFailureRetries
    ) {
      retryCount += 1;
      process.stderr.write(
        `\n[loyalty-dev] Shopify CLI exited before dev server was ready; retrying ${retryCount}/${maxQuickFailureRetries}...\n`,
      );
      setTimeout(startShopifyCli, 2000);
      return;
    }

    clearInterval(manifestPoll);
    configWrite = configWrite.then(() => writeTunnelUrl("", { force: true }));
    await configWrite;

    if (signal) {
      process.exitCode = signal === "SIGINT" ? 130 : 143;
    } else {
      process.exitCode = code ?? 1;
    }
  });
}

configWrite = configWrite.then(() => writeTunnelUrl("", { force: true }));
startManifestPolling();
startShopifyCli();

for (const signal of ["SIGINT", "SIGTERM"]) {
  process.on(signal, () => child?.kill(signal));
}
